# Configurazione Ensemble per Coding Agents
# Questo file controlla il numero di agenti e la strategia di aggregazione

ensemble:
  # Numero di agenti identici che lavorano in parallelo
  num_agents: 100
  
  # Configurazione base per ogni agente
  model: "gpt-4o-mini"
  base_temperature: 0.7
  
  # Esecuzione parallela
  parallel_execution: true
  max_concurrent: 20  # Massimo 20 chiamate API simultanee per evitare rate limiting
  timeout_seconds: 30  # Timeout per ogni agente
  continue_on_error: true  # Continua anche se alcuni agenti falliscono
  min_successful_responses: 60  # Almeno 60 risposte valide richieste

# Strategie di diversificazione tra agenti
diversification:
  # Varia la temperatura tra gli agenti per avere risposte diverse
  vary_temperature: true
  temperature_range: [0.3, 1.0]
  temperature_distribution: "uniform"  # uniform, normal, random
  
  # Varia top_p sampling
  vary_top_p: true
  top_p_range: [0.8, 1.0]
  
  # Varia i prompt (opzionale)
  vary_prompts: false
  prompt_variations: []

# Strategia di aggregazione delle risposte
aggregation:
  # Metodo primario: majority_vote, weighted_vote, meta_synthesis, statistical
  method: "majority_vote"
  
  # Configurazione Majority Voting
  majority_vote:
    # Percentuale minima di consenso richiesta
    min_consensus: 60
    
    # Come determinare se due risposte sono "uguali"
    similarity_method: "semantic"  # exact, semantic, hybrid
    similarity_threshold: 0.85  # Per semantic similarity (0-1)
    
    # Se nessuna maggioranza chiara, usa fallback
    fallback_strategy: "meta_synthesis"  # meta_synthesis, highest_confidence, random
    
  # Estrazione della confidenza dalle risposte (opzionale)
  extract_confidence: true
  confidence_prompt: |
    On a scale of 0-100, how confident are you in this answer?
    Provide only the number.

# Output e logging
output:
  format: "detailed"  # simple, detailed, debug
  include_metadata: true
  
  # Metadati da includere nella risposta
  metadata_fields:
    - num_agents_executed
    - num_successful_responses
    - consensus_percentage
    - execution_time_seconds
    - response_distribution
    - individual_responses  # Include tutte le risposte per debugging
    - temperature_used
  
  # Logging
  log_individual_responses: true
  log_file: "logs/ensemble_execution.log"

# Performance e costi
performance:
  # Cache delle risposte identiche
  enable_caching: true
  cache_duration_seconds: 3600
  
  # Early stopping se consenso raggiunto prima
  early_stopping: true
  early_stop_threshold: 0.9  # Ferma se 90% agenti d'accordo
  early_stop_min_responses: 30  # Minimo 30 risposte prima di early stop
  
  # Rate limiting
  respect_rate_limits: true
  requests_per_minute: 100

# Profili predefiniti per scenari diversi
profiles:
  # Testing veloce
  quick_test:
    num_agents: 10
    max_concurrent: 10
    min_consensus: 60
    
  # Sviluppo standard
  development:
    num_agents: 50
    max_concurrent: 15
    min_consensus: 60
    
  # Production standard
  production:
    num_agents: 100
    max_concurrent: 20
    min_consensus: 70
    
  # Alta accuratezza
  high_accuracy:
    num_agents: 200
    max_concurrent: 25
    min_consensus: 80
    temperature_range: [0.2, 0.8]  # Meno variabilità
    
  # Massima diversità
  high_diversity:
    num_agents: 100
    max_concurrent: 20
    min_consensus: 60
    temperature_range: [0.1, 1.5]  # Più variabilità
