write_poem:
  description: >
    Write a poem about how MAgNet is awesome.
    Ensure the poem is engaging and adheres to the specified sentence count of {sentence_count}.
  expected_output: >
    A beautifully crafted poem about MAgNet, with exactly {sentence_count} sentences.
  agent: poem_writer
